/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


 */
package string;

import java.util.HashMap;

/**
 * Created by poorvank on 20/09/16.
 */
public class FindDifference {

    public char findTheDifference(String s, String t) {

        HashMap<Character,Integer> map = new HashMap<>();

        for (Character c : t.toCharArray()) {
            if(map.containsKey(c)) {
                map.put(c,map.get(c)+1);
            }
            else {
                map.put(c,1);
            }
        }

        for (Character c : s.toCharArray()) {
            map.put(c,map.get(c)-1);
        }

        char extraChar='\0';
        for (Character c : map.keySet()) {
            if(map.get(c)>0) {
                extraChar = c;
            }
        }

        return extraChar;

    }
}
